version: '3.7'

services:
  postgres:
    image: postgres:16.2-alpine
    container_name: learn-deploy
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5454:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_USER}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

volumes: postgres_db:./postgres
